app = "roblox-gemini-bridge-flask"

kill_signal = "SIGINT"
kill_timeout = "5s"

[processes]
  app = "gunicorn app:app --bind :5000 --worker-tmp-dir /dev/shm --workers 3" # Run gunicorn on port 5000

[experimental]
  allowed_public_ports = []
  auto_rollback_machines = true

[build]
  builder = "paketobuildpacks/builder:base" # Explicitly use Paketo buildpacks

[env]
  GEMINI_API_KEY = ""
  DATABASE_URL = ""

[http_service]
  internal_port = 5000 # <--- IMPORTANT: Make sure this is 5000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] # <--- Use the 'app' process defined above
  [http_service.ports]
    handlers = ["http"]
    port = 80
  [[http_service.tcp_checks]]
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
    port = 5000