# fly.toml app configuration file generated for render-gemini-server-repo-sparkling-pond-7470 on 2025-02-20T02:19:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'render-gemini-server-repo-sparkling-pond-7470'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] # Keep 'app' process

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes] # Define processes section
  app = "/app/.venv/bin/gunicorn app:app --bind :8080 --workers 3" # Full path to gunicorn